services:
  notetaker-ai-api:
    container_name: notetaker-ai-drf
    image: notetaker-ai:latest
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 8001:8001
    depends_on:
      - ollama
    extra_hosts:
      - "localhost:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/routes/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s

  # Optional demo container (kept similar to original expectations)
  notetaker-demo:
    container_name: notetaker-demo
    image: notetaker-demo:latest
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - demo/.env.demo
    ports:
      - 7860:7860
    depends_on:
      - notetaker-ai-api
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - ./demo:/app/demo

  # Ollama setup (optional, for local models)
  ollama:
    container_name: ollama_server
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
